### ISSUE TITLE
Country bar chart does not display the correct figures

### ISSUE THREAD

**Issue by ntncmch** [epicentre-msf/gtfcc-ocv-app#25]
The country bar chart works fine when displaying number of requests but fail when switching to doses. See screenshots below for doses shipped:

The map and table are consistent :
![Screenshot 2023-11-17 at 15 46 33](https://github.com/epicentre-msf/gtfcc-ocv-app/assets/1412115/8e456a8f-fd0c-48b2-8ed7-72c89d379371)

![Screenshot 2023-11-17 at 15 47 49](https://github.com/epicentre-msf/gtfcc-ocv-app/assets/1412115/27f08370-7e8d-4e5e-b433-066f66b54c31)

but the bar chart is different

![Screenshot 2023-11-17 at 15 46 43](https://github.com/epicentre-msf/gtfcc-ocv-app/assets/1412115/2069c8ee-8216-4df4-8fae-144bbae6bec4)

**Comment by PaulC91** [comment]
closed in https://github.com/epicentre-msf/gtfcc-ocv-app/pull/27. thanks Hugo!
