### ISSUE TITLE
Problem with colour palette in time-series when filtering

### ISSUE THREAD

**Issue by ntncmch** [epicentre-msf/gtfcc-ocv-app#26]
Palette is consistent between charts but not after filtering by status.

![Screenshot 2023-11-17 at 16 16 29](https://github.com/epicentre-msf/gtfcc-ocv-app/assets/1412115/7181c300-d6ea-497d-ad24-ae34abcef8c9)

![Screenshot 2023-11-17 at 16 16 47](https://github.com/epicentre-msf/gtfcc-ocv-app/assets/1412115/2c0d06e8-f7c6-4f3d-bdbf-19c94b4a152e)

**Comment by PaulC91** [comment]
closed in https://github.com/epicentre-msf/gtfcc-ocv-app/pull/27. thanks Hugo!
